user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
